const path = {
  home: '/',
  detailArtist: '/artist/:nameId',
  detailAlbum: '/album/:nameId',
  detailPlaylist: '/playlist/:nameId',
  forgotPassword: '/forgotPassword',
  myPlaylist: '/myPlaylist',
  myAlbum: '/artist/myAlbum',
  chart: '/chart',
  dashboard: '/',
  user: '/user',
  search: '/search/',
  profile: '/user/profile',
  changePassword: '/user/changepassword',
  historyTransaction: '/user/transaction-history',
  jobRequest: '/user/job-request',
  login: '/login',
  register: '/register',
  logout: '/logout',
  productDetail: ':nameId',
  cart: '/cart',
  expertDetail: '/expertDetail/:nameId',
  validateEmail: '/validate-email/:token',
  promoteToArtist: '/promote-to-artist',
  paymentResponse: '/payment-response',
  becomeArtist: '/user/become-artist',

  //Expert
  expert: '/expert',
  expertProfile: '/expert/profile',
  expertChangePassword: '/expert/changepassword',
  expertTransactionHistory: '/expert/transaction-history',
  expertAnalytics: '/expert/analytics',
  expertBookings: '/expert/bookings',
  expertShowListPost: '/expert/list-post',
  expertDashboard: '/expert/dashboard',
  expertWithdraw: '/expert/withdraw',

  //Expert
  artist: '/artist',
  artistProfile: '/artist/profile',
  artistChangePassword: '/artist/changepassword',
  artistTransactionHistory: '/artist/transaction-history',
  artistAnalytics: '/artist/analytics',
  artistBookings: '/artist/bookings',
  artistShowListPost: '/artist/list-post',
  artistDashboard: '/artist/dashboard',
  artistWithdraw: '/artist/withdraw',

  //Admin
  admin: '/admin',
  adminProfile: '/admin/profile',
  adminListUser: '/admin/users-management',
  adminListMajor: '/admin/major-management',
  adminVerifyExpert: '/admin/verify-expert',
  adminListDocument: '/admin/document-management',
  adminListTransaction: '/admin/transaction-management',
  adminListReport: '/admin/report-management',
  adminDashBoard: '/admin/dashboard',
  adminWithdraw: '/admin/withdraw-management',
  adminMusic: '/admin/music-management',
  adminGenre: '/admin/genre-management'
}

export default path
